field: acb1177c-7912-4c43-8906-b8645e5893fb # Content Blocks
fieldLayouts:
  4e11db44-037d-4667-a3f8-c673475e7598:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4f114960-57b1-421c-b634-b64362113d07 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df9f3ac4-7608-4729-bcd4-0405b9a96935
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 385fbb37-7afe-4770-8dab-8c610e388e9b
        userCondition: null
fields:
  4f114960-57b1-421c-b634-b64362113d07: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:cf4f295c-7351-4308-bc93-bcd1f7378561' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:cf4f295c-7351-4308-bc93-bcd1f7378561' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: imageOnly
name: 'Image Only'
sortOrder: 3
