field: acb1177c-7912-4c43-8906-b8645e5893fb # Content Blocks
fieldLayouts:
  9e1869e4-d8f9-4cc5-a2aa-a907e37194ae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b1784cae-4a05-45b9-ae48-d57bfdac0c4d # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d0cfa0a-b2c5-47fe-acd8-0a1a9c9461b6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 81b45c35-948f-4efb-b0db-6a99efa5962d
        userCondition: null
fields:
  b1784cae-4a05-45b9-ae48-d57bfdac0c4d: # Text
    columnSuffix: cqewoirv
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: textOnly
name: 'Text Only'
sortOrder: 1
