fieldLayouts:
  15f86b17-68b2-43bb-b554-1645249f84be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e0b1eab4-2868-4a9a-9c77-44b3971b4c00
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 16b7b362-5e79-46fc-ad98-0c9d63416a5e # Product Line
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2df7df53-0645-4774-86f2-5b69b84abe54
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 2cbf6175-9fd2-4c1b-878b-b824dac4990e # Cover Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89ce097a-462f-4b87-abee-aee6180941bc
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 4d48894c-7511-4d0d-b47f-581d53b924dc
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: a317d4bd-b383-4b1a-aa8e-906e4643f142 # Model Kits
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
