defaultPlacement: end
fieldLayouts:
  79eeff29-dabb-4420-96b6-468d3e076b3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: f7c7b402-e8d9-47df-9896-8a1f4742e5d7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 904600d6-7ae8-4a8c-9606-7edba338ab1d
        userCondition: null
handle: productLine
name: 'Product Line'
siteSettings:
  3f6b2556-6fdd-48b4-b28b-a625bcb4132d: # Craft
    hasUrls: true
    template: null
    uriFormat: 'product-line/{slug}'
structure:
  maxLevels: null
  uid: 9209404e-c97b-4125-bd8a-6f5d933a8fae
