fieldLayouts:
  63580d0a-498b-43d2-9c24-41bd99fa2e0b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d9fd5d76-bb86-445f-8aba-615a6a2bcabe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 38220135-aa2c-4dec-9b29-f349e16fea9d
        userCondition: null
fs: awsS3
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
